### ISSUE TITLE
debug_traceChain return error

### ISSUE THREAD

**Issue by forencen** [kcc-community/kcc#25]
in websoket:

```
{"id": 1, "method": "debug_subscribe", "params": ["traceChain", "0xcdb15c", "0xcdb15d", {"tracer":"callTracer", "timeout": "200s"}]}
```
node return :
```
{
    "jsonrpc": "2.0",
    "method": "debug_subscription",
    "params": {
        "subscription": "0x54c78f84f76ea97d99d537732d3d1b0c",
        "result": {
            "block": "0xcdb15d",
            "hash": "0xd2c4993d166b14e59a038d5d02a96b01865346b714e5c5cfce2aa5323e0edd43",
            "traces": [
                {
                    "error": "execution timeout"
                }
            ]
        }
    }
}
```

This result is different from debug_traceBlockByNumber.

debug_traceBlockByNumber return like this:
```
{
    "jsonrpc": "2.0",
    "method": "debug_traceBlockByNumber",
    "params": [
        "0xcdb15d",
         {"tracer": "callTracer", "timeout": "200s"}
    ],
    "id": 1
}
```
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
        {
            "result": {
                "type": "CALL",
                "from": "0x3a9c5e0c405b039eeb6f2f7ccca5bfccb2bc69a3",
                "to": "0xfdfce767add9dcf032cbd0de35f0e57b04495324",
                "value": "0x0",
                "gas": "0xbe134",
                "gasUsed": "0x2070e",
                "input": "0xe2bbb15800000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000003c0eca9fb0293aa3e2a",
                "output": "0x",
                "time": "139.752927ms",
                "calls": [
                    {
                        "type": "STATICCALL",
                        "from": "0xfdfce767add9dcf032cbd0de35f0e57b04495324",
                        "to": "0xa232918ca4064667f9230eb30cd593c7c03959d7",
                        "gas": "0xb780d",
                        "gasUsed": "0x9c6",
                        "input": "0x70a08231000000000000000000000000fdfce767add9dcf032cbd0de35f0e57b04495324",
                        "output": "0x000000000000000000000000000000000000000000005f3f23c2b68b7c6cf8b5"
                    },
                    {
                        "type": "CALL",
                        "from": "0xfdfce767add9dcf032cbd0de35f0e57b04495324",
                        "to": "0x2ca48b4eea5a731c2b54e7c3944dbdb87c0cfb6f",
                        "value": "0x0",
                        "gas": "0xb12a0",
                        "gasUsed": "0x4c63",
                        "input": "0x40c10f19000000000000000000000000fdfce767add9dcf032cbd0de35f0e57b04495324000000000000000000000000000000000000000000000003c51c70de4220ec06",
                        "output": "0x"
                    },
                    {
                        "type": "CALL",
                        "from": "0xfdfce767add9dcf032cbd0de35f0e57b04495324",
                        "to": "0xa232918ca4064667f9230eb30cd593c7c03959d7",
                        "value": "0x0",
                        "gas": "0xa9a61",
                        "gasUsed": "0x32ec",
                        "input": "0x23b872dd0000000000000000000000003a9c5e0c405b039eeb6f2f7ccca5bfccb2bc69a3000000000000000000000000fdfce767add9dcf032cbd0de35f0e57b044953240000000000000000000000000000000000000000000003c0eca9fb0293aa3e2a",
                        "output": "0x"
                    }
                ]
            }
        }
    ]
}
```

**Comment by forencen** [comment]
I need to batch process  block's trace

**Comment by junnmm** [comment]
Hi @forencen, 

Thanks for your report.   
What you have seen is reasonable with the current implementations. 

Both `TraceChain` and `TraceBlockByNumber` are implemented in [api.go](https://github.com/kcc-community/kcc/blob/092856267067dd78b527a773f5b240d5c9f5693a/eth/tracers/api.go). However, they are implemented in a slightly different way:  

- If you are fetching traces of multiple blocks with `TraceChain`,  the node will use multiple goroutines to trace multiple blocks simultaneously.  As you can see from [the code](https://github.com/kcc-community/kcc/blob/092856267067dd78b527a773f5b240d5c9f5693a/eth/tracers/api.go#L257-L287), each goroutine is responsible for a single block.  Let's say, if you are tracing a single block with `TraceChain`,  we will only start a single goroutine and all the transactions will be sequentially processed one by one in this single goroutine.  

- If you are fetching traces of a block with `TraceBlockByNumber`, the node will also use multiple goroutines,  but [each goroutine](https://github.com/kcc-community/kcc/blob/092856267067dd78b527a773f5b240d5c9f5693a/eth/tracers/api.go#L481-L496) for a transaction in your block.  As transactions in a single block are processed concurrently, it would cost less time.   

Our Suggestions: 

- Use `TraceBlockByNumber`  if possible  

If you really have to use `TraceChain`:  

- Increase the timeout because you have only a single goroutine for the whole block. 


Regards.

**Comment by forencen** [comment]
Hello @junnmm. thank you for your reply. and I've browsed the code.

but, fetching traces of a block with `TraceBlockByNumber` one by one is too slow.
Can I get faster speed by modify the node code.
Do you have any good suggestions to modify the node code ?

Look forward to your reply

Thanks!

**Comment by junnmm** [comment]
> Hello @junnmm. thank you for your reply. and I've browsed the code.
> 
> but, fetching traces of a block with `TraceBlockByNumber` one by one is too slow. Can I get faster speed by modify the node code. Do you have any good suggestions to modify the node code ?
> 
> Look forward to your reply
> 
> Thanks!

Hi, Sorry for the delay. 

Of course, you can always do whatever you want with the codes. 

I would suggest first taking a look at the upstream repo (i.e: go-ethereum),  maybe they have already come up with a better solution.   

If you really want to add more goroutines to process transactions concurrently in `TraceChain`, don't forget to use profiling tools to find the real bottleneck.  IMO, tracing is both a CPU-intensive and IO-intensive task.  

Regards.
